FROM mysql:8
LABEL author="Shin, Ilsuk <actionshin@gmail.com>"
LABEL date="2022-08-13"

ENV LC_ALL=C.UTF-8
ENV character-set-server=utf8
ENV collation-server=utf8_general_ci
ENV default-character-set=utf8
ENV default-collation=utf8_general_ci
ENV TZ=Asia/Seoul

EXPOSE 3306
CMD ["mysqld"]